name: Add New User
description: Start the onboarding process of a person into the SCRF ecosystem.
title: "Persons Full Name"
labels: []
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!
  - type: textarea
    id: transcript
    attributes:
      label: Chat Application Transcripts
      description: Please copy and paste the contents of the generated transcript file if there is one.