name: Add New User
description: Start the onboarding process of a person into the SCRF ecosystem.
title: "Persons Full Name"
labels: []
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!
  - type: input
    id: full-name
    attributes:
      label: Full Name      
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Preferred Contact Method
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: chat-username
    attributes:
      label: Discord Chat Username
      description: user#1234      
    validations:
      required: false
  - type: input
    id: forum-username
    attributes:
      label: Discourse Forum Username
      description: user#1234      
    validations:
      required: true
  - type: input
    id: github-username
    attributes:
      label: Discourse Forum Username      
  - type: dropdown
    id: vertical
    attributes:
      label: Vertical
      description: What vertical does this person belong to?
      options:
        - None
        - Content
        - Engagement
        - Discovery
        - Outreach
        - Operations
    validations:
      required: true
  - type: dropdown
    id: role-level
    attributes:
      label: Role Level
      description: What role level does this person have?
      options:
        - Community
        - Contributor
        - Core
        - Lead
        - Head
  - type: textarea
    id: transcript
    attributes:
      label: Chat Application Transcripts
      description: Please copy and paste the contents of the generated transcript file if there is one.