name: Simple
description: Just one click away!
title: "Persons Full Name"
labels: []
assignees:
  - SirAh0
body:
- type: markdown
  attributes:
    value: "## Thank you for contributing to our project!"