name: Simple
description: Just one click away!
title: "Persons Full Name"
labels: []
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!

  - type: input
    id: full-name
    attributes:
      label: Full Name      
    validations:
      required: true